solutions/lab12/vinier/config/routes.rb
Vinier::Application.routes.draw do
  resources :wines do 
    get :search, :on => :collection
  end

  get "home/index", :as => 'home'
  
  root :to => 'wines#index'

end

solutions/lab12/vinier/app/models/wine.rb
# Encoding: utf-8

class Wine < ActiveRecord::Base
  belongs_to :wine_type
  
  # validates_presence_of :name
  validates :name, :presence => true

  # validates_numericality_of :vintage, :greater_than => 1900
  validates :vintage, :numericality => { :greater_than => 1900 }

  # validates_numericality_of :quantity, :greater_than => 0
  validates :vintage, :numericality => { :greater_than => 0 }

  # validates_inclusion_of :rating, :in => 0..100, :if => :rating
  validates :rating, :inclusion => 0..100, :if => :rating

  # validates_uniqueness_of :code_saq
  validates :code_saq, :uniqueness => true
  
  def drink_in_year
    vintage + years_to_maturity unless vintage.nil? || years_to_maturity.nil?
  end  
end

solutions/lab12/vinier/app/models/wine_type.rb
class WineType < ActiveRecord::Base
  has_many :wines
end

solutions/lab12/vinier/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

solutions/lab12/vinier/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @allo = 'le monde'
  end

end

solutions/lab12/vinier/app/controllers/wines_controller.rb
class WinesController < ApplicationController
  # GET /wines
  # GET /wines.xml
  def index
    @wines = Wine.order(:name).paginate :per_page => 5, :page => params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @wines }
      format.js { render :search }
    end
  end
  
  def search
    @wines = Wine.where("name LIKE ?", '%'+params[:query]+'%').order(:name).paginate :per_page => 5, :page => params[:page]
    respond_to do |format|
      format.html { render :index }
      format.js
    end
  end

  # GET /wines/1
  # GET /wines/1.xml
  def show
    @wine = Wine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @wine }
    end
  end

  # GET /wines/new
  # GET /wines/new.xml
  def new
    @wine = Wine.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @wine }
    end
  end

  # GET /wines/1/edit
  def edit
    @wine = Wine.find(params[:id])
  end

  # POST /wines
  # POST /wines.xml
  def create
    @wine = Wine.new(params[:wine])

    respond_to do |format|
      if @wine.save
        format.html { redirect_to(@wine, :notice => 'Wine was successfully created.') }
        format.xml  { render :xml => @wine, :status => :created, :location => @wine }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @wine.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /wines/1
  # PUT /wines/1.xml
  def update
    @wine = Wine.find(params[:id])

    respond_to do |format|
      if @wine.update_attributes(params[:wine])
        format.html { redirect_to(@wine, :notice => 'Wine was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @wine.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1
  # DELETE /wines/1.xml
  def destroy
    @wine = Wine.find(params[:id])
    @wine.destroy

    respond_to do |format|
      format.html { redirect_to(wines_url) }
      format.xml  { head :ok }
    end
  end
end

solutions/lab12/vinier/app/helpers/application_helper.rb
module ApplicationHelper
end

solutions/lab12/vinier/app/helpers/home_helper.rb
module HomeHelper
end

solutions/lab12/vinier/app/helpers/wines_helper.rb
module WinesHelper
  def label_image_url(wine)
    "http://www.saq.com/wcsstore/saqcom/images_produits/#{wine.code_saq}_g.jpg"
  end
end

solutions/lab12/vinier/app/views/home/index.html.erb
<%= link_to 'Liste des vins', wines_path %>

<h1>Accueil</h1>
<p>Find me in app/views/home/index.html.erb</p>

<h2>Solutionnaire</h2>

<dt>Requête 3</dt>
<dd><%= Wine.where(:vintage => 2007).count %></dd>

<dt>Requête 4</dt>
<dd>
  <pre>
    vin = Wine.new
    vin.vintage = 2011
    vin.name = 'Les Florières'
    vin.save
    
    Wine.create(:vintage => 2012, :name => 'Castle Rock', 
      :wine_type => WineType.find_by_title('Pinot noir'))
  </pre>
</dd>

<dt>Requête 5</dt>
<dd><%= Wine.where(:vintage => 2007).count %></dd>

<dt>Requête 6</dt>
<dd><%= Wine.where(:vintage => 2007, :color => 'Rouge').count %></dd>

<dt>Requête 7</dt>
<dd>
  <%= Wine.joins(:wine_type).where('wine_types.title = ?', 'Chardonnay').count %>
  ou
  <%= Wine.joins(:wine_type).where(:wine_types => { :title => 'Chardonnay'}).count %>
</dd>

<dt>Requête 8</dt>
<dd>
  <pre>
    vin = Wine.find_by_name('Bourgogne Chardonnay Ropiteau')
    vin.update_attribute(:rating, 75)
    vin.update_attributes(:rating => 75)
    vin.rating = 75
    vin.save
  </pre>
</dd>

solutions/lab12/vinier/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vinier</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>

<body>
  <div id="container">
		<%= yield %>
	</div>
</body>

</html>

solutions/lab12/vinier/app/views/wines/_contact.html.erb
<div style="float:right">
	<%= mail_to '', 'Suggérer à un ami', :subject => "Suggestion de vin: #{@wine.name}" %>
</div>

solutions/lab12/vinier/app/views/wines/_form.html.erb
<%= form_for(@wine) do |f| %>
  <% if @wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% @wine.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :wine_type %><br />
    <%= f.collection_select :wine_type_id, WineType.all, :id, :title %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :vintage %><br />
    <%= f.text_field :vintage %>
  </div>
  <div class="field">
    <%= f.label :acquired_on %><br />
    <%= f.date_select :acquired_on %>
  </div>
  <div class="field">
    <%= f.label :winery %><br />
    <%= f.text_field :winery %>
  </div>
  <div class="field">
    <%= f.label :appellation %><br />
    <%= f.text_field :appellation %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :years_to_maturity %><br />
    <%= f.text_field :years_to_maturity %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.text_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :code_saq %><br />
    <%= f.text_field :code_saq %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

solutions/lab12/vinier/app/views/wines/_list.html.erb
<div id="wines">
  <p>
    <%= will_paginate wines %>
  </p>

  <table>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Vintage</th>
      <th>Quantity</th>
      <th>Rating</th>
      <th>A boire en</th>
    </tr>

  <% wines.each do |wine| %>
    <tr>
  	  <td><%= link_to image_tag(label_image_url(wine), :height => 100), label_image_url(wine), :target => 'label' %></td>
      <td>
        <h3><%= link_to wine.name, wine %></h3>
        <p>
          <%= wine.winery %><br/>
          <%= wine.country %><br/>
          <%= wine.color %><br/>
          <%= wine.wine_type.try(:title) %>
        </p>
      </td>
      <td><%= wine.vintage %></td>
      <td><%= wine.quantity %></td>
      <td><%= number_to_percentage wine.rating, :precision => 0 %></td>
      <td><%= wine.drink_in_year %></td>
    </tr>
  <% end %>
  </table>
</div>

<script type="text/javascript" charset="utf-8">
  $(function() {
    $('.pagination a').attr('data-remote', true);
  });
</script>

solutions/lab12/vinier/app/views/wines/edit.html.erb
<h1>Editing wine</h1>

<%= render 'form' %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

solutions/lab12/vinier/app/views/wines/index.html.erb
<%= link_to 'Accueil', :controller => 'home' %> | <%= link_to 'Accueil', home_path %>

<h1>Liste des vins</h1>

<%= form_tag search_wines_path, :method => :get, :remote => true do %>
	<%= text_field_tag :query, params[:query] %>
	<%= submit_tag "Chercher" %>
	<%= link_to 'Tous', wines_path %>
<% end -%>

<%= render 'list', :wines => @wines %>

<br />

<%= link_to 'New Wine', new_wine_path %>

solutions/lab12/vinier/app/views/wines/new.html.erb
<h1>New wine</h1>

<%= render 'form' %>

<%= link_to 'Back', wines_path %>

solutions/lab12/vinier/app/views/wines/search.js.erb
$('#wines').replaceWith('<%= escape_javascript render 'list', :wines => @wines %>');

solutions/lab12/vinier/app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<%= render "contact", :wine => @wine %>

<p>
  <b>Name:</b>
  <%= @wine.name %>
</p>

<p>
  <b>Type:</b>
  <%= @wine.wine_type.try(:title) %>
</p>

<p>
  <b>Vintage:</b>
  <%= @wine.vintage %>
</p>

<p>
  <b>Acquired on:</b>
  <%= @wine.acquired_on %>
</p>

<p>
  <b>Winery:</b>
  <%= @wine.winery %>
</p>

<p>
  <b>Appellation:</b>
  <%= @wine.appellation %>
</p>

<p>
  <b>Color:</b>
  <%= @wine.color %>
</p>

<p>
  <b>Years to maturity:</b>
  <%= @wine.years_to_maturity %>
</p>

<p>
  <b>Quantity:</b>
  <%= @wine.quantity %>
</p>

<p>
  <b>Rating:</b>
  <%= @wine.rating %>
</p>

<p>
  <b>Notes:</b>
  <%= @wine.notes %>
</p>

<p>
  <b>Country:</b>
  <%= @wine.country %>
</p>

<p>
  <b>Code saq:</b>
  <%= @wine.code_saq %>
</p>


<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Destroy', @wine, :confirm => 'Are you sure?', :method => :delete %> |
<%= link_to 'Back', wines_path %>